### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by hehern** [matssteinweg/PIXOR#2]
when i run the code by "python evaluate_model.py ", I got the following error:
Traceback (most recent call last):
  File "evaluate_model.py", line 412, in <module>
    eval_dict = evaluate_model(pixor, data_loader, distance_ranges=[70, 50, 30], iou_thresholds=[0.5, 0.6, 0.7, 0.8, 0.9])
  File "evaluate_model.py", line 227, in evaluate_model
    batch_predictions = model(batch_data)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/data/PIXOR/PIXOR.py", line 244, in forward
    x_b = self.basis_block(x)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/data/PIXOR/PIXOR.py", line 28, in forward
    x = self.conv1(x)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

can you help me ?

**Comment by matssteinweg** [comment]
It seems like this error occurred due to inconsistencies of the tensors' devices. As I don't have access to a GPU on my computer, I ran the evaluation code on the CPU. I might have missed to include full GPU-support for the evaluation function. You should be able to fix it by setting the device properly for all tensors created in the evaluation function. 

I will fix this in the repository as soon as possible. Let me know if you have any further questions about the implementation.

**Comment by hehern** [comment]
thx
