### ISSUE TITLE
Problem while training

### ISSUE THREAD

**Issue by apfelbaumx** [matssteinweg/PIXOR#3]
Hey there,
i´ve stumbled across ur project and wanted to recreated it. i am somewhat of a nooby, so i´ve run into a problem while trying to train the model. 

here is the error: 
Traceback (most recent call last):
  File "train_model.py", line 273, in <module>
    history = train_model(pixor, optimizer, scheduler, data_loader, n_epochs=n_epochs)
  File "train_model.py", line 163, in train_model
    moving_loss = {'train': metrics['train_loss'][-1], 'val': metrics['val_loss'][-1]}
IndexError: list index out of range

from my understanding it fails while trying to access the prior element in the dictionary. 

i would be glad if u could help me out. thanks in advance!
take care

**Comment by matssteinweg** [comment]
Hej, 
I just had a quick look at the code. Unfortunately, it's been quite a while since I last worked with the code. It seems like an error when accessing an empty list in the first iteration. Maybe just try and set some initial values in line 157. 

Let me know if you encounter other problems with the code.

**Comment by apfelbaumx** [comment]
hey,

thank you for the quick response! it works with some initial values. if i run into other problems i´ll let u know.

stay safe and take care mate

**Comment by hoangduyloc** [comment]
@apfelbaumx  
Did you retrain and get the approximate results like the author?
